a=float(input("enter the first number:"))
b=float(input("enter the second number:"))
print("\n")
print("addition",a+b)
print("subtraction",a-b)
print("multiplication",a*b)
print("division",a/b)
input("press enter to exit")